In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('E:/maharshtra/2014 Form 20.xlsx')

In [3]:
df.head()

,Serial No. of Polling Station,PB Name,Keshavrao Beniram Katre,Prof. Dahiwade Rameshchandr a Dattatray,Mungantiwar Sudhir Sachhidanand,Mulchandani Ghansham Khushimal,Waman Dauji Zade,Singh Rajesh Durgasingh,Ad. Harshal Kumar Chiplunkar,Ad. Anand Sikandar Lakde,...,Vandana Ajay Chauhan,Santosh Muka Ramteke,Prajyot Devidas Nale,Wasudev Parshuram Pipare,Sanjay Nilkanth Gawande,Total of Valid Votes,No. of Rejected Votes,NOTA,TOTAL,No. of Tendered Votes
0,NaN,NaN,SHS,CPI(M),BJP,INC,NCP,BSP,MNS,APOI,...,RPI,RP(K),IND,IND,IND,NaN,NaN,NaN,NaN,NaN
1,1,Payali Bhatali,20,1,161,25,0,48,0,3,...,1,0,1,1,0,283,0,3.0,286.0,0.0
2,2,Payali Bhatali,34,2,561,86,7,31,4,3,...,0,2,3,3,5,772,0,7.0,779.0,0.0
3,3,Mohurli,18,26,393,82,28,73,3,2,...,1,4,10,3,9,684,0,9.0,693.0,0.0
4,4,Adegaon,4,3,195,50,18,2,2,0,...,2,1,1,0,0,379,0,3.0,382.0,0.0

In [4]:
df['PB Name'][0]
df1 = df.sort_values('PB Name')
df1

,Serial No. of Polling Station,PB Name,Keshavrao Beniram Katre,Prof. Dahiwade Rameshchandr a Dattatray,Mungantiwar Sudhir Sachhidanand,Mulchandani Ghansham Khushimal,Waman Dauji Zade,Singh Rajesh Durgasingh,Ad. Harshal Kumar Chiplunkar,Ad. Anand Sikandar Lakde,...,Vandana Ajay Chauhan,Santosh Muka Ramteke,Prajyot Devidas Nale,Wasudev Parshuram Pipare,Sanjay Nilkanth Gawande,Total of Valid Votes,No. of Rejected Votes,NOTA,TOTAL,No. of Tendered Votes
318,318,AASHTI,7,0,465,183,2,2,0,4,...,0,3,10,0,3,681,0,8.0,689.0,0.0
94,94,AJAYPUR,9,2,160,122,2,2,1,4,...,2,4,2,1,3,462,0,2.0,464.0,0.0
93,93,AJAYPUR,5,4,394,70,3,2,1,2,...,1,1,1,8,1,543,0,2.0,545.0,0.0
271,271,AMTI,2,4,241,274,5,9,0,0,...,0,1,8,0,0,552,0,2.0,554.0,0.0
147,147,ARVAT,8,25,446,213,9,27,0,0,...,0,1,5,3,11,750,0,4.0,754.0,0.0
4,4,Adegaon,4,3,195,50,18,2,2,0,...,2,1,1,0,0,379,0,3.0,382.0,0.0
15,15,Alevahi Urf Navegaon,1,1,178,116,8,0,0,0,...,3,1,1,2,1,318,0,3.0,321.0,0.0
43,43,Ambora,0,1,179,88,0,0,0,1,...,0,1,1,0,1,279,0,1.0,280.0,0.0
289,289,BABRALA,1,1,132,102,6,16,1,2,...,0,1,0,3,1,267,0,2.0,269.0,0.0
269,269,BAMANI,3,0,375,229,6,7,1,2,...,1,1,5,3,0,634,0,3.0,637.0,0.0
266,266,BAMANI,6,3,387,265,5,1,0,2,...,1,1,5,2,4,690,0,7.0,697.0,0.0
267,267,BAMANI,3,0,205,153,0,18,0,0,...,0,0,1,0,0,382,0,1.0,383.0,0.0
268,268,BAMANI,6,1,246,249,7,9,0,1,...,2,4,7,2,0,538,0,3.0,541.0,0.0
270,270,BAMANI,4,0,336,189,3,0,1,0,...,1,0,3,3,1,542,0,3.0,545.0,0.0
241,241,BEJGAON,6,7,291,253,8,10,2,7,...,4,1,4,4,1,681,0,5.0,686.0,0.0
240,240,BEJGAON,2,4,272,252,2,2,2,2,...,1,5,3,3,4,567,0,6.0,573.0,0.0
245,245,BELGAON UARF YERGAON,2,3,240,247,21,24,2,2,...,1,2,1,10,1,642,0,5.0,647.0,0.0
246,246,BELGAON UARF YERGAON,2,2,160,99,21,2,4,4,...,1,0,0,1,0,407,0,0.0,407.0,0.0
316,316,BHATADI,5,2,111,236,7,0,2,4,...,2,2,1,3,3,392,0,3.0,395.0,0.0
120,120,BHAVRALA,3,5,394,132,33,2,1,0,...,1,0,1,1,4,579,0,3.0,582.0,0.0
286,286,BOMBAD,2,5,193,172,24,191,4,8,...,4,6,0,3,2,620,0,6.0,626.0,0.0
287,287,BOMBAD,6,4,429,237,25,17,0,2,...,1,3,2,1,3,734,0,5.0,739.0,0.0
288,288,BOMBAD,8,4,400,125,74,34,1,3,...,1,5,6,2,4,671,0,6.0,677.0,0.0
294,294,BONDALA BUJ,3,3,274,213,20,0,3,3,...,2,2,0,1,3,528,0,5.0,533.0,0.0
293,293,BONDALA KHURD,1,6,272,211,20,1,2,3,...,0,4,4,6,1,532,0,2.0,534.0,0.0
278,278,BORD BORKAR,2,2,280,165,3,4,0,1,...,3,1,1,4,0,467,0,3.0,470.0,0.0
279,279,BORD DIKSHIT,10,3,146,168,4,1,0,1,...,1,1,1,1,0,339,0,0.0,339.0,0.0
280,280,BORD ZULLURWAR,0,6,369,136,12,2,8,0,...,2,0,6,4,1,557,0,3.0,560.0,0.0
86,86,BORDA,8,6,318,122,3,69,4,6,...,6,4,0,3,2,781,0,0.0,781.0,0.0
220,220,Ballarapur,2,3,207,184,3,25,4,0,...,2,0,0,0,0,431,0,4.0,435.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,53,Urjanagar,26,2,348,106,11,59,4,4,...,0,1,0,1,3,579,0,8.0,587.0,0.0
82,82,Urjanagar,79,20,361,114,4,129,3,5,...,4,2,13,0,4,755,0,7.0,762.0,0.0
54,54,Urjanagar,26,4,527,125,11,71,7,9,...,0,1,5,0,3,816,0,10.0,826.0,0.0
49,49,Urjanagar,4,2,158,61,3,22,3,0,...,0,0,0,0,1,258,0,1.0,259.0,0.0
24,24,Ushrala Chak,2,1,286,183,10,1,2,1,...,1,0,1,0,0,493,0,2.0,495.0,0.0
23,23,Ushrala Chak,4,4,251,146,4,1,1,3,...,1,2,1,3,3,476,0,1.0,477.0,0.0
88,88,VALNI,4,8,200,27,2,0,13,6,...,0,4,0,1,1,498,0,3.0,501.0,0.0
87,87,VAYGON MOKASA,3,5,74,37,3,3,4,5,...,1,0,1,0,1,389,0,2.0,391.0,0.0
319,319,VELAVA MAL,9,5,289,275,9,30,15,4,...,3,5,5,3,3,663,0,8.0,671.0,0.0
233,233,VIRAI,2,4,427,305,6,106,5,7,...,2,1,2,5,0,887,0,2.0,889.0,0.0
136,136,VISAPUR,7,1,304,216,4,27,21,3,...,0,1,6,2,2,594,0,6.0,600.0,0.0
142,142,VISAPUR,3,3,443,276,0,14,23,0,...,0,2,10,0,3,788,0,1.0,789.0,0.0
135,135,VISAPUR,7,4,314,430,6,18,11,2,...,5,0,5,1,3,808,0,5.0,813.0,0.0
140,140,VISAPUR,2,2,294,169,6,9,22,1,...,1,4,9,2,2,531,0,4.0,535.0,0.0
139,139,VISAPUR,2,7,191,161,6,18,2,1,...,0,0,8,2,5,403,0,0.0,403.0,0.0
138,138,VISAPUR,4,6,196,198,1,22,10,1,...,0,0,16,0,7,461,0,4.0,465.0,0.0
137,137,VISAPUR,2,0,207,79,0,1,3,0,...,0,1,3,0,0,299,0,1.0,300.0,0.0
134,134,VISAPUR,4,9,375,303,5,12,14,2,...,9,2,4,6,1,746,0,6.0,752.0,0.0
143,143,VISAPUR,1,3,166,94,0,5,1,0,...,0,1,6,1,1,280,0,2.0,282.0,0.0
141,141,VISAPUR,1,3,248,141,1,4,2,1,...,3,1,0,1,3,433,0,4.0,437.0,0.0
41,41,Vadholi,4,2,268,56,1,42,5,3,...,4,2,4,3,2,480,0,3.0,483.0,0.0
36,36,Varavat,12,9,218,92,2,111,2,6,...,1,2,9,1,2,553,0,5.0,558.0,0.0
37,37,Varavat,35,14,154,68,4,98,2,10,...,2,1,4,2,2,441,0,0.0,441.0,0.0
0,NaN,NaN,SHS,CPI(M),BJP,INC,NCP,BSP,MNS,APOI,...,RPI,RP(K),IND,IND,IND,NaN,NaN,NaN,NaN,NaN
340,Total No.of votes recorded at polling Stations,NaN,2552,1566,103261,59927,1854,10299,1960,749,...,451,562,1089,788,628,193472,0,1373.0,194845.0,0.0
341,No. of votes recorded on postal ballot papers,NaN,3,5,457,191,13,45,4,1,...,1,1,0,0,0,746,55,10.0,811.0,0.0
342,Total votes\npolled,NaN,2555,1571,103718,60118,1867,10344,1964,750,...,452,563,1089,788,628,194218,55,NaN,195656.0,0.0
343,Place :-,NaN,Mul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,Date :-,NaN,"19 th Oct., 2014",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Returning Officer,NaN,NaN,NaN
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,72- Ballarpur Lagislative Assembly Constituency,NaN,NaN,NaN,NaN

In [15]:
print("Length of the unique names : ", len(set(df['PB Name'])))
for i in range(len(df['PB Name'])):
    if df1['PB Name'][i] == df['PB Name'][i+1]:

Length of the unique names :  176