In [1]:
import pandas as pd

In [4]:
df = pd.read_excel('/f_drive/Pdf of Constituencies/maharashtra (ballarpur)/Maharashtra(ballarpur).xlsx')
df.head()

,Assembly Constituency,Part No,Serial No,Name,Epic ID,Geder,Age
0,72,1,1,अंजनाबाई यादव तोडासे,,F,84
1,72,1,18,अभिमान रघुनाथ मडावी,JVW0940940,M,35
2,72,1,38,अनिल तुकाराम. भसारकर,MT/26/156/0000756,M,44
3,72,1,39,अरुणा अनिल भसारकर,,F,38
4,72,1,53,अर्चना भाउराव पेटकर,JVW0941153,F,38

In [19]:
# df.groupby(['Part No']).count()
df.nunique()
df2 = df.drop_duplicates()

In [22]:
# df2.nunique()
df2.groupby(['Part No']).count()

         Assembly Constituency  Serial No  Name  Epic ID  Geder   Age
Part No
1                          437        437   437      437    437   437
2                         1040       1040  1040     1040   1040  1040
3                          936        936   936      936    936   936
4                          507        507   507      507    507   507
5                          662        662   662      662    662   662
6                          193        193   193      193    193   193
7                         1142       1142  1142     1142   1142  1142
8                         1229       1229  1229     1229   1229  1229
9                         1027       1027  1027     1027   1027  1027
10                         262        262   262      262    262   262
11                         727        727   727      727    727   727
12                         992        992   992      992    992   992
13                         897        897   897      897    897   897
14                         960        960   960      960    960   960
15                         354        354   354      354    354   354
16                         609        609   609      609    609   609
17                         602        602   602      602    602   602
18                         842        842   842      842    842   842
19                         769        769   769      769    769   769
20                         440        440   440      440    440   440
21                         786        786   786      786    786   786
22                         604        604   604      604    604   604
23                         586        586   586      586    586   586
24                         571        571   571      571    571   571
25                         927        927   927      927    927   927
26                         910        910   910      910    910   910
27                         961        961   961      961    961   961
28                         250        250   250      250    250   250
29                         260        260   260      260    260   260
30                         130        130   130      130    130   130
...                        ...        ...   ...      ...    ...   ...
335                        741        741   741      741    741   741
336                        896        896   896      896    896   896
337                        622        622   622      622    622   622
338                        713        713   713      713    713   713
339                        374        374   374      374    374   374
340                        521        521   521      521    521   521
341                        436        436   436      436    436   436
342                        464        464   464      464    464   464
343                        705        705   705      705    705   705
344                        706        706   706      706    706   706
345                        278        278   278      278    278   278
346                        893        893   893      893    893   893
347                        469        469   469      469    469   469
348                        585        585   585      585    585   585
349                        552        552   552      552    552   552
350                        800        800   800      800    800   800
351                        749        749   749      749    749   749
352                        690        690   690      690    690   690
353                        645        645   645      645    645   645
354                        720        720   720      720    720   720
355                        542        542   542      542    542   542
356                        717        717   717      717    717   717
357                        420        420   420      420    420   420
358                        377        377   377      377    377   377
359                       1008       1008  1008     1008   1008  1008
360                        415        415   415      415    415   415
361                        576        576   576      576    576   576
362                        786        786   786      786    786   786
363                        609        609   609      609    609   609
364                        524        524   524      524    524   524

[364 rows x 6 columns]

In [49]:
import string
alpha = string.ascii_uppercase
alphaA = alpha[:6]
alphaA

'ABCDEF'

In [141]:
hindiUnicodes = []
print(u'\u0905\u0906\u0907')
# forty = [i for i in range(40)]
# six = [i for i in range(6)]
for i in range(40):
    hindiUnicodes.append('\\u09'+str(i).zfill(2))
for j in range(6):
    hindiUnicodes.append('\\u091'+alphaA[j])
    hindiUnicodes.append('\\u092'+alphaA[j])
#     hindiUnicodes.append('093'+alphaA[j])

अआइ

In [142]:
str(29).zfill(2)[0]
len(hindiUnicodes)
hindiUnicodes = hindiUnicodes[4:]
# print(u''+hindiUnicodes[0])भ
# hindiUnicodes = hindiUnicodes[भ]

In [220]:
# print(u'{}'.format(hindiUnicodes[0]))
a = 'u0904'
u'\u0904'

'ऄ'

In [226]:
# print(u''%(hindiUnicodes[0]))
hindiC = 'अइउऋऌएओअंआईऊॠॡऐऔअःऑॲकखगघङचछजझञयशहटठडढणरषतथदधनलसपफबभमव'
len(hindiC)
# hindiC[1]

'इ'